config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'sessions#new'
  get 'term-of-service', to: 'static_pages#term_of_service'
  get '/password/:id', to: 'password_edit#edit'
  get '/home',    to: 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_edit, only:[:edit, :update]
  resources :microposts, only: [:new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed                    
  has_many :followers, through: :passive_relationships, source: :follower
  validates :email, presence: true
  validates :full_name,  presence: true
  validates :user_name,  presence: true
  has_secure_password
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :not_logged_in_user, only: :new
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Instagramへようこそ！"
      redirect_to @user
    else
      render "new"
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to signup_url
  end
  
  def show
    @user = User.find(params[:id])
    @url = request.url
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  def password
    user = User.find_by(id: params[:id])
  end
    
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private
  
    def user_params
      params.require(:user).permit(:email, :full_name, :user_name,
                                    :password, :password_confirmation,
                                    :web_site, :introduce, :phone, :gender)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :full_name , 'フルネーム(必須入力)' %>
      <%= f.text_field :full_name, class: 'form-control' %>
      
      <%= f.label :user_name, 'ユーザーネーム(必須入力)' %>
      <%= f.text_field :user_name, class: 'form-control' %>
      
      <%= f.label :web_site, 'ウェブサイト' %>
      <%= f.text_field :web_site, class: 'form-control' %>
      
      <%= f.label :introduce, '自己紹介' %>
      <%= f.text_area :introduce, class: 'form-control' %>
      
      <p class='private_info'>非公開情報</p>
      <%= f.label :email ,'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone ,'電話番号' %>
      <%= f.phone_field :phone, class: 'form-control' %>
      
      <%= f.label :gender ,'性別' %>
      <%= f.radio_button :gender, 1 %>
      <%= f.label :gender, '男性', {value: :male} %>
      <%= f.radio_button :gender, 2 %>
      <%= f.label :gender, '女性', {value: :female} %>
      <%= f.radio_button :gender, 3 %>
      <%= f.label :gender, 'その他', {value: :other} %>
      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>
    
    <%= link_to 'アカウントを削除する', @user, method: :delete, data:{ confirm: "本当に削除しますか？" } %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Instagram</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>
    
      <%= f.label :full_name, "フルネーム" %>
      <%= f.text_field :full_name, class: 'form-control' %>
      
      <%= f.label :user_name, "ユーザーネーム" %>
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
    <p>アカウントをお持ちの方はこちら <%= link_to "ログインする", login_path %></p>
    <%= link_to "利用規約", term_of_service_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.user_name %>
        <% if current_user && current_user.id == params[:id].to_i %>
          <%= link_to edit_user_path(current_user) do %>
            <p class="edit_user_button edit_prof_button">プロフィールを編集</p>
          <% end %>
          <%= link_to "/password/#{params[:id]}" do %>
            <p class="edit_user_button">パスワードを変更</p>
          <% end %>
        <% end %>
      </h1>
    </section>
  </aside>
  <div>
    <h2 class="font_in_show name"><%= @user.full_name %></h2>
    <h2 class="font_in_show introduce">自己紹介</h2>
    <h2 class="font_in_show"><%= @user.introduce %></h2> 
  </div>
  <div class="account_details_wrap">
    <div class="account_details_box">
      <h2>投稿</h2>
      <h2><%= @user.microposts.count %></h2>
      <h2>件</h2>
    </div>
    <div class="account_details_box">
      <a href="<%= followers_user_path(@user) %>">
        フォロワー<br>
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
        <br>人
      </a>
    </div>
    <div class="account_details_box">
      <a href="<%= following_user_path(@user) %>">
        フォロー中<br>
        <strong id="following" class="stat">
          <%= @user.following.count %>
        </strong>
        <br>人
      </a>
    </div>
  </div>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <ol class="microposts" style = "list-style-type:none;">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.user_name %></h1>
      <span><%= link_to "プロフィール画面へ", @user %></span>
      <span><b>投稿数:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to user.user_name, user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
</div>