config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'sessions#new'
  get 'term-of-service', to: 'static_pages#term_of_service'
  get '/password/:id', to: 'password_edit#edit'
  get '/home',    to: 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_edit, only:[:edit, :update]
  resources :microposts, only: [:new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_edit_controller.rb
class PasswordEditController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "パスワードを変更しました"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  
end

app/helpers/password_edit_helper.rb
module PasswordEditHelper
end

app/views/password_edit/edit.html.erb
<% provide(:title, "Edit password") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user, url: password_edit_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>