config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'sessions#new'
  get 'term-of-service', to: 'static_pages#term_of_service'
  get '/password/:id', to: 'password_edit#edit'
  get '/home',    to: 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_edit, only:[:edit, :update]
  resources :microposts, only: [:new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<% if logged_in? %>
  <footer class="footer">
    <nav>
      <div>
        <%= link_to new_micropost_path do %>
          <i class="far fa-plus-square"></i>
          <h><br>投稿</h>
        <% end %>
      </div>
    </nav>
  </footer>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to home_path, id: "logo" do %>
        <i class="fab fa-instagram"></i>
        <h1 class="instagram">Instagram Clone Site</h1>
      <% end %>
    <% else %>
      <%= link_to root_path, id: "logo" do %>
        <i class="fab fa-instagram"></i>
        <h1 class="instagram">Instagram Clone Site</h1>
      <% end %>
    <% end %> 
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to @current_user do %>
              <i class="fas fa-user"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
      <% if logged_in? %>
      <%= link_to "ログアウト", logout_path, method: :delete, class: "logout"%>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>